workspace:
  base: /go
  path: src/github.com/ldejager/microbadger-notify

pipeline:
  build:
    image: golang
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
      - GOPATH=/go
    commands:
      - export PATH=$PATH:$GOPATH/bin
      - go get
      - go build -a -o microbadger-notify
    when:
      branch: master
      event: push
  publish:
    image: plugins/docker
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ldejager/microbadger-notify
    file: Dockerfile
    tag:
      - ${DRONE_COMMIT:0:8}
      - latest
  notify:
    image: ldejager/microbadger-notify
    environment:
      - MB_REPOSITORY=microbadger-notify
      - MB_TOKEN=SKbaX4-yp1IJY0tbxlGO1hKjhRk=
    when:
      status: success
